(()=>{
const params=new URLSearchParams(location.search),designMode=params.get('mode')==='design',tool=document.body.dataset.maker;
const idKeys=['primary','secondary','accent','theme','paperSize','orientation','customW','customH','idWidth','idHeight','setsPerRow','cutGap','cardGap','zoom','radius','showCutGuides','showFoldGuide','guideColor','guideStroke','guideOffset','idFont','nameWeight','logoSize','background','paperMargin','photoWidth','photoHeight','nameScale','roleScale','detailScale','idScale','policyScale','nameCase'];
const priceKeys=Object.keys(defaultsSafe());
function defaultsSafe(){return tool==='price'?defaults:{}}
function copyKeys(obj,keys){return Object.fromEntries(keys.filter(k=>obj[k]!==undefined).map(k=>[k,obj[k]]))}
let activePreset=null;
function lock(){document.documentElement.classList.toggle('staff-mode',!designMode);document.documentElement.classList.remove('preset-loading');}
function apply(p){if(!p||typeof p.companyName!=='string'||typeof p.brandName!=='string')throw Error('Invalid preset');activePreset=p;
 if(tool==='id'){Object.assign(state,copyKeys(factoryState,idKeys),copyKeys(p.idDesign||{},idKeys));state.companyName=p.companyName;state.amayzaLogo=p.logo||'';state.schoolLogo=p.branchLogo||'';state.form.branchSite='CUSTOM';state.form.branchCustom=p.brandName;state.form.photoShape=p.idDesign?.photoShape||p.photoShape||'rounded';for(const it of state.ids){it.amayzaLogo=state.amayzaLogo;it.schoolLogo=state.schoolLogo;it.branchSite='CUSTOM';it.branchCustom=p.brandName;it.photoShape=state.form.photoShape}render();}
 else {Object.assign(state,copyKeys(factoryState,priceKeys),copyKeys(p.priceDesign||{},priceKeys));state.brandName=p.brandName;state.logo=p.logo||'';inputs();rows();preview();}
 const note=document.getElementById('presetNotice');note.textContent=designMode?'Design draft · '+p.name:'Preset: '+p.name+' · Fill in your details, then download or print.';lock();
}
function snapshot(){return tool==='id'?{...copyKeys(state,idKeys),photoShape:state.form.photoShape}:copyKeys(state,priceKeys)}
const notice=document.createElement('div');notice.id='presetNotice';notice.setAttribute('role','status');notice.style.cssText='padding:12px 20px;background:#fff9de;border-bottom:1px solid #e0d7a5;font:14px Arial';notice.textContent='Loading preset…';document.querySelector('header').after(notice);
if(designMode){const bar=document.createElement('div');bar.className='preset-savebar';bar.style.cssText='padding:12px 20px;background:#edf2f8;display:flex;gap:12px;align-items:center';const b=document.createElement('button');b.textContent='Save this design to preset';b.onclick=()=>{if(!activePreset)return;const hasError=tool==='id'?document.getElementById('idLayoutWarning').textContent:layout().error;if(hasError){notice.textContent='Fix the paper layout warning before saving this preset.';return;}parent.postMessage({kind:'amayza-save-design',presetId:activePreset.id,tool,design:snapshot(),assets:{logo:tool==='id'?state.amayzaLogo:state.logo,branchLogo:tool==='id'?state.schoolLogo:activePreset.branchLogo,brandName:tool==='id'?(state.form.branchCustom||activePreset.brandName):state.brandName}},location.origin);notice.textContent='Design saved to draft. Use Publish in Admin Studio when ready.'};bar.append(b);document.querySelector('header').after(bar);window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent||e.data?.kind!=='amayza-load-draft')return;apply(e.data.preset)});parent.postMessage({kind:'amayza-designer-ready'},location.origin);}
else{fetch('presets.json?v='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Cannot load presets');return r.json()}).then(data=>{const requested=params.get('preset');const p=data.presets.find(p=>p.id===requested)||data.presets.find(p=>p.brand===brandKey)||data.presets[0];apply(p)}).catch(()=>{notice.textContent='Presets could not load. Refresh the page before creating an ID or tag.';document.documentElement.classList.add('preset-error');});}
})();
