const $=id=>document.getElementById(id);
const brandKey=new URLSearchParams(location.search).get('brand')==='beverage'?'beverage':'perfume',key='amayza-price-v1-'+brandKey;
const defaults={primary:brandKey==='perfume'?'#171717':'#715200',secondary:brandKey==='perfume'?'#d4af37':'#ffd435',background:'#ffffff',width:6,height:4.5,columns:3,paperSize:'A4',orientation:'portrait',paperW:210,paperH:297,margin:10,gap:5,guides:true,guideStyle:'crop',guideColor:'#8b8b8b',guideOffset:0,guideStroke:.2,zoom:75,style:'bold',logoSize:10,radius:3,showNotes:true,showBrand:true,autoFit:true,titleFont:'Arial',bodyFont:'Arial',priceFont:'Arial',titleSize:17,bodySize:10,priceSize:27,titleWeight:'900',bodyWeight:'400',priceWeight:'900',align:'center',nameCase:'original'};
let state={...defaults,brandName:brandKey==='perfume'?'D.A.Y. & COLE SCENTS':'AMAYZA BEVERAGES',logo:brandKey==='perfume'?'daycole.png':'',items:brandKey==='perfume'?[{name:'SIGNATURE SCENT',price:199,notes:'50 mL • Sample price'},{name:'EAU DE PARFUM',price:299,notes:'100 mL • Sample price'}]:[{name:'ICED LEMON TEA',price:59,notes:'16 oz • Sample price'},{name:'MANGO COOLER',price:79,notes:'22 oz • Sample price'}]};
const factoryState=JSON.parse(JSON.stringify(state));
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved)state={...state,...saved};const prefs=JSON.parse(localStorage.getItem('amayza-brand-'+brandKey)||'null');if(prefs){state.brandName=prefs.name||state.brandName;state.logo=prefs.logo||state.logo}}catch{}
const numeric=new Set(['width','height','columns','paperW','paperH','margin','gap','guideOffset','guideStroke','zoom','logoSize','radius','titleSize','bodySize','priceSize']);
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function save(){try{localStorage.setItem(key,JSON.stringify(state));localStorage.setItem('amayza-brand-'+brandKey,JSON.stringify({name:state.brandName,logo:state.logo}))}catch{$('status').textContent='Browser storage is full. Save an editable file before closing.'}}
function dimensions(){let [w,h]=({A4:[210,297],SHORT:[215.9,279.4],LONG:[215.9,330.2],CUSTOM:[state.paperW,state.paperH]})[state.paperSize]||[210,297];if(state.orientation==='landscape')[w,h]=[h,w];return {w,h}}
function layout(){const {w,h}=dimensions(),tw=state.width*10,th=state.height*10,usableW=w-2*state.margin,usableH=h-2*state.margin,rows=Math.floor((usableH+state.gap)/(th+state.gap));let error='';if(state.columns*tw+(state.columns-1)*state.gap>usableW+.01)error='Tags exceed the paper width. Reduce columns, tag width, cutting space, or margins.';else if(rows<1)error='Tag height exceeds the printable area. Reduce tag height or margins.';else if(state.guides&&state.guideOffset+1.5>Math.min(state.gap/2,state.margin))error='Cutting guides need more space. Increase cutting space or reduce guide offset.';return {w,h,tw,th,rows:Math.max(1,rows),perPage:Math.max(1,rows)*state.columns,error}}
function guide(w,h){if(!state.guides)return '';const o=state.guideOffset,stroke=state.guideStroke,color=esc(state.guideColor),x=-o,y=-o,r=w+o,b=h+o,l=Math.min(1.5,state.gap/2-o);if(state.guideStyle!=='crop')return `<svg class="cut-guide" style="left:0;top:0;width:${w}mm;height:${h}mm" viewBox="0 0 ${w} ${h}"><rect x="${x}" y="${y}" width="${w+2*o}" height="${h+2*o}" fill="none" stroke="${color}" stroke-width="${stroke}" ${state.guideStyle==='dashed'?'stroke-dasharray="1.2 .8"':''}/></svg>`;let d=`M${x-l} ${y}H${x} M${x} ${y-l}V${y} M${r} ${y}H${r+l} M${r} ${y-l}V${y} M${x-l} ${b}H${x} M${x} ${b}V${b+l} M${r} ${b}H${r+l} M${r} ${b}V${b+l}`;return `<svg class="cut-guide" style="left:0;top:0;width:${w}mm;height:${h}mm" viewBox="0 0 ${w} ${h}"><path d="${d}" stroke="${color}" stroke-width="${stroke}" fill="none"/></svg>`}
function productName(s){if(state.nameCase==='upper')return s.toUpperCase();if(state.nameCase==='title')return s.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());return s}
function priceEdit(key,value,index){return `<span contenteditable="plaintext-only" role="textbox" tabindex="0" data-tag-key="${key}" data-tag-index="${index}" aria-label="Preview ${key} · Tag ${index+1}" title="Click to edit">${esc(value)}</span>`}
function bindPricePreview(){document.querySelectorAll('[data-tag-key]').forEach(el=>{
 el.oninput=()=>{const key=el.dataset.tagKey,i=Number(el.dataset.tagIndex),value=el.textContent;if(key==='brandName'){state.brandName=value;document.querySelectorAll('[data-tag-key="brandName"]').forEach(other=>{if(other!==el)other.textContent=value;});}else if(key==='price'){const n=Number(value.replace(/[₱,\s]/g,''));if(!Number.isFinite(n)||n<0){el.setAttribute('aria-invalid','true');return;}el.removeAttribute('aria-invalid');state.items[i].price=n;}else state.items[i][key]=value;inputs();rows();$('bulk').value=state.items.map(it=>`${it.name} | ${it.price} | ${it.notes}`).join('\n');save();};
 el.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();el.blur();}};el.onblur=e=>{if(!e.relatedTarget?.closest('#sheet'))preview();};
})}
function tag(it,l){const index=state.items.indexOf(it);const classic=state.style==='classic',compact=state.style==='compact';return `<div class="tag-wrap" style="width:${l.tw}mm;height:${l.th}mm">${guide(l.tw,l.th)}<article class="tag" style="width:100%;height:100%;border-radius:${state.radius}mm;background:${esc(state.background)}"><div class="tag-header" style="background:${classic?'transparent':'var(--primary)'};color:${classic?'var(--primary)':'white'};min-height:${compact?6:8}mm;padding:${compact?2:4}px 10px;font-family:${esc(state.bodyFont)}">${state.logo?`<img style="height:${state.logoSize}mm;max-height:${Math.max(4,l.th*.3)}mm;width:auto" src="${esc(state.logo)}" alt="${esc(state.brandName)}">`:priceEdit('brandName',state.brandName,index)}</div><div class="tag-body" style="text-align:${state.align};padding:${compact?4:8}px 10px"><div class="tag-name" style="font-family:${esc(state.titleFont)};font-size:${state.titleSize}px;font-weight:${state.titleWeight}">${priceEdit('name',productName(it.name),index)}</div>${state.showNotes?`<div class="tag-note" style="font-family:${esc(state.bodyFont)};font-size:${state.bodySize}px;font-weight:${state.bodyWeight}">${priceEdit('notes',it.notes,index)}</div>`:''}</div><div class="tag-price" style="font-family:${esc(state.priceFont)};font-size:${state.priceSize}px;font-weight:${state.priceWeight};padding:${compact?3:7}px">₱${priceEdit('price',Number(it.price).toLocaleString('en-PH',{maximumFractionDigits:2}),index)}</div>${state.showBrand?`<div class="tag-footer" style="font-family:${esc(state.bodyFont)};font-size:${Math.max(6,state.bodySize-1)}px;font-weight:${state.bodyWeight}">${priceEdit('brandName',state.brandName,index)}</div>`:''}</article></div>`}
function fit(){if(!state.autoFit)return;document.querySelectorAll('.tag').forEach(el=>{const name=el.querySelector('.tag-name'),note=el.querySelector('.tag-note'),body=el.querySelector('.tag-body');for(let n=0;n<30;n++){if(body.scrollHeight<=body.clientHeight+1&&name.scrollWidth<=name.clientWidth+1&&el.scrollHeight<=el.clientHeight+1)break;for(const t of [name,note])if(t)t.style.fontSize=Math.max(6,parseFloat(t.style.fontSize)*.94)+'px';const price=el.querySelector('.tag-price');price.style.fontSize=Math.max(8,parseFloat(price.style.fontSize)*.96)+'px'}})}
function preview(){const l=layout(),sheet=$('sheet');document.documentElement.style.setProperty('--primary',state.primary);document.documentElement.style.setProperty('--secondary',state.secondary);const pages=[];for(let i=0;i<state.items.length;i+=l.perPage)pages.push(state.items.slice(i,i+l.perPage));sheet.style.zoom=state.zoom/100;sheet.innerHTML=pages.map((items,i)=>`<div class="printPage" data-page="${i+1}" style="width:${l.w}mm;height:${l.h}mm;padding:${state.margin}mm;grid-template-columns:repeat(${state.columns},${l.tw}mm);grid-auto-rows:${l.th}mm;gap:${state.gap}mm">${items.map(it=>tag(it,l)).join('')}</div>`).join('');$('count').textContent=`${state.items.length} tags · ${pages.length} pages`;$('status').textContent=l.error;$('print').disabled=!!l.error;$('download').disabled=!!l.error||!pages.length;$('zoomValue').textContent=state.zoom+'%';let n=Number($('exportPage').value)||1;$('exportPage').innerHTML=pages.map((_,i)=>`<option>${i+1}</option>`).join('');$('exportPage').value=Math.min(n,pages.length)||1;let ps=$('printPageSize');if(!ps){ps=document.createElement('style');ps.id='printPageSize';document.head.appendChild(ps)}ps.textContent=`@page{size:${l.w}mm ${l.h}mm;margin:0}`;bindPricePreview();fit();save()}
function rows(){$('rows').innerHTML=state.items.map((it,i)=>`<tr><td><input aria-label="Product ${i+1}" data-i="${i}" data-field="name" value="${esc(it.name)}"></td><td><input aria-label="Price ${i+1}" type="number" min="0" data-i="${i}" data-field="price" value="${esc(it.price)}"></td><td><input aria-label="Notes ${i+1}" data-i="${i}" data-field="notes" value="${esc(it.notes)}"></td><td><button data-remove="${i}" aria-label="Remove ${esc(it.name)}">Remove</button></td></tr>`).join('');$('rows').querySelectorAll('input').forEach(el=>el.oninput=()=>{state.items[el.dataset.i][el.dataset.field]=el.dataset.field==='price'?Math.max(0,Number(el.value)||0):el.value;preview()});$('rows').querySelectorAll('button').forEach(el=>el.onclick=()=>{state.items.splice(Number(el.dataset.remove),1);rows();preview()})}
function generate(){const lines=$('bulk').value.split(/\r?\n/).filter(l=>l.trim());const result=lines.map(line=>{const [name,price,notes]=line.split('|').map(s=>s.trim());const value=price?Number(price.replace(/[₱,\s]/g,'')):Number($('defaultPrice').value);if(!name||!Number.isFinite(value)||value<0)throw Error('Check product names and prices. Prices must be zero or higher.');return {name,price:value,notes:notes||''}});if(!result.length)throw Error('Enter at least one product.');state.items=result;rows();preview();return {count:result.length}}
function inputs(){for(const id of ['brandName',...Object.keys(defaults)]){const el=$(id);if(!el)continue;if(el.type==='checkbox')el.checked=!!state[id];else el.value=state[id]}}
for(const id of ['brandName',...Object.keys(defaults)]){const el=$(id);if(!el)continue;el.addEventListener('input',()=>{let v=el.type==='checkbox'?el.checked:el.value;if(numeric.has(id)){v=Number(v);if(!Number.isFinite(v)||v<Number(el.min||1)||v>Number(el.max||4))return;}state[id]=v;preview()})}
$('bulk').value=state.items.map(i=>`${i.name} | ${i.price} | ${i.notes}`).join('\n');$('generate').onclick=()=>{try{generate()}catch(e){$('status').textContent=e.message}};$('logo').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{state.logo=r.result;preview()};r.readAsDataURL(f)};
$('print').onclick=()=>{if(!state.items.length){$('status').textContent='Generate tags first.';return}if(layout().error)return;window.print()};
$('download').onclick=async()=>{const pageNumber=$('exportPage').value,target=document.querySelector(`[data-page="${pageNumber}"]`);if(!target)return;const b=$('download');b.disabled=true;b.textContent='Preparing JPG…';try{const c=await html2canvas(target,{scale:3,backgroundColor:'#fff',onclone:d=>{d.getElementById('sheet').style.zoom='1';const clean=d.createElement('style');clean.textContent='[data-tag-key]{outline:none!important;background:transparent!important}';d.head.append(clean);}});const a=document.createElement('a');a.download=`AMAYZA-price-tags-page-${pageNumber}.jpg`;a.href=c.toDataURL('image/jpeg',.96);a.click()}catch(e){$('status').textContent='Unable to download. Please print or save as PDF.'}finally{b.disabled=!!layout().error;b.textContent='Download JPG sheet'}};
$('saveFile').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({amayzaPriceVersion:2,...state},null,2)],{type:'application/json'}));a.download='AMAYZA-'+brandKey+'-price-tags.json';a.click();URL.revokeObjectURL(a.href)};
$('importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.items)||!d.items.every(i=>typeof i.name==='string'&&Number.isFinite(Number(i.price))&&Number(i.price)>=0))throw Error();const next={...state};for(const k of [...Object.keys(defaults),'brandName','logo']){if(d[k]===undefined)continue;const el=$(k);if(numeric.has(k)){const v=Number(d[k]);if(!Number.isFinite(v)||v<Number(el.min||1)||v>Number(el.max||4))throw Error();next[k]=v}else if(typeof defaults[k]==='boolean'){if(typeof d[k]!=='boolean')throw Error();next[k]=d[k]}else if(el?.tagName==='SELECT'){if(!Array.from(el.options).some(o=>o.value===String(d[k])))throw Error();next[k]=d[k]}else if(typeof d[k]==='string')next[k]=d[k]}next.items=d.items.map(i=>({name:i.name,price:Number(i.price),notes:String(i.notes||'')}));state=next;inputs();$('bulk').value=state.items.map(i=>`${i.name} | ${i.price} | ${i.notes}`).join('\n');rows();preview()}catch{$('status').textContent='Invalid AMAYZA price-tag file.'}};r.readAsText(f)};
$('resetDesign').onclick=()=>{Object.assign(state,defaults);inputs();preview()};inputs();rows();preview();
if(document.modelContext?.registerTool)document.modelContext.registerTool({name:'generate_price_tags',description:'Generate price tags from product lines. Does not print or download.',inputSchema:{type:'object',properties:{products:{type:'string'}},required:['products'],additionalProperties:false},execute(input){if(typeof input.products!=='string')throw Error('Products must be text');const old=$('bulk').value;$('bulk').value=input.products;try{return generate()}catch(e){$('bulk').value=old;throw e}}});
